### ISSUE TITLE
netty4客户端似乎不支持超时？报warn

### ISSUE THREAD

**Issue by depyuka** [dubboclub/dubbo-plus#1]
配置好之后，连接完成后提示如下：
19:31:40.629 [ZkClient-EventThread-17-192.168.2.10:2181] WARN  io.netty.bootstrap.Bootstrap - Unknown channel option: SO_TIMEOUT=30000

**Comment by bieberHe** [comment]
这个确实是疏漏了，在最新的代码里面替换成了CONNECT_TIMEOUT_MILLIS，谢谢指出问题。

**Comment by Justice-love** [comment]
SO_TIMEOUT只对OIO有效
